### ISSUE TITLE
Websocket client reconnect.

### ISSUE THREAD

**Issue by laper32** [bedroombuilds/python2rust#1]
https://github.com/bedroombuilds/python2rust/blob/main/23_websockets_client/rust/ws_client/src/main.rs#L42

Here, if server goes wrong, or just disconnected, we want to reconnect, what should we do to perform it pretty?
Looks like currently we just report server is gone.

Do we have to write another function or do something special to handle it?
Currently I do not have any idea about it...

**Comment by mike-kfed** [comment]
One simple solution is to factor out what is currently the `main()` function into a new function, e.g. `talk_to_websocket()` that returns some flag if a retry can/should be done, and then inside main call the `talk_to_websocket()` in a loop kinda like this:

```rust
fn main() {
loop {
   let retry = talk_to_websocket();
   if !retry {break;}
}
}
```

**Comment by laper32** [comment]
Thanks, I will try
